/*
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.santander.sal.dbox.dto;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import lombok.Data;

/**
 * Pet
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "petType", visible = true)
@JsonSubTypes({
		@JsonSubTypes.Type(value = Cat.class, name = "pussyCat"),
		@JsonSubTypes.Type(value = Dog.class, name = "plutoDog"), })
@Data
public abstract class Pet implements Serializable {
	private static final long serialVersionUID = 1L;
	private String name;

}
