/*
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.santander.sal.dbox.dto;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;

/**
 * RsvXO
 */
@Data
public class RsvXO implements Serializable {
	private static final long serialVersionUID = 1L;
	private String name;
	private Pet pet;
	private Date aenderDatum;

}
