/*
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package nl.zoo.dto;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonTypeName;

import lombok.Data;

@Data
@JsonTypeName("Cat")
public class Cat extends Pet implements Serializable {
	private static final long serialVersionUID = 1L;

	private String preferredGardenToPeeIn;

}
